spring:
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3330/TripTip?serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  h2.console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: true

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create # 과제 제출용 설정
#    properties:
#      hibernate:
#        format_sql: true
##        dialect: org.hibernate.dialect.Dialect
#    defer-datasource-initialization: true
#    database: mysql

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false

#  boot:
#    admin:
#      client:
#        url: http://localhost:58080
#        instance:
#          name: jayang

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  api-docs:
    path: /swagger